<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="products.aspx.cs" Inherits="products" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
    <h2 style="color: rgb(0, 0, 0); background: none rgb(255, 255, 255); font-weight: normal; margin: 1em 0px 0.25em; overflow: hidden; padding: 0px; border-bottom: 1px solid rgb(162, 169, 177); font-size: 1.5em; font-family: &quot;Linux Libertine&quot;, Georgia, Times, serif; line-height: 1.3; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span id="Retail_goods" class="mw-headline">Retail goods</span></h2>
    <p style="margin: 0.5em 0px; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        Amazon product lines include several media (<a href="https://en.wikipedia.org/wiki/Book" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Book">books</a>, DVDs, music CDs,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/VHS" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="VHS">videotapes</a>, and software), apparel, baby products,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Consumer_electronics" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Consumer electronics">consumer electronics</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Cosmetics" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Cosmetics">beauty products</a>, gourmet food, groceries, health and personal-care items, industrial &amp; scientific supplies, kitchen items,<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Jewelry" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Jewelry">jewelry</a><span>&nbsp;</span>and 
        watches, lawn and garden items, musical instruments,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Sports_equipment" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Sports equipment">sporting goods</a>, tools, automotive items and toys &amp; games.</p>
    <p style="margin: 0.5em 0px; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        The company launched amazon.com Auctions, a web auctions service, in March 1999. However, it failed to chip away at the large market share of the industry pioneer,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/EBay" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="EBay">eBay</a>. Later, the company launched a fixed-price<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Marketplace" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Marketplace">marketplace</a><span>&nbsp;</span>business, zShops, in September 1999, and the now defunct partnership with<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Sotheby's" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Sotheby's">Sotheby&#39;s</a>, called<span>&nbsp;</span><i>Sothebys.amazon.com</i>, in November. Auctions and zShops evolved into<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Amazon_Marketplace" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Amazon Marketplace">Amazon 
        Marketplace</a>, a service launched in November 2000 that let customers sell used books, CDs, DVDs, and other products alongside new items. As of October&nbsp;2014, Amazon Marketplace is the largest of its kind, followed by similar marketplaces from<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Sears" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Sears">Sears</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Rakuten.com" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Rakuten.com">Rakuten</a>, and<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Newegg" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Newegg">Newegg</a>.</p>
    <h2 style="color: rgb(0, 0, 0); background: none rgb(255, 255, 255); font-weight: normal; margin: 1em 0px 0.25em; overflow: hidden; padding: 0px; border-bottom: 1px solid rgb(162, 169, 177); font-size: 1.5em; font-family: &quot;Linux Libertine&quot;, Georgia, Times, serif; line-height: 1.3; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span id="Amazon_Prime" class="mw-headline">Amazon Prime</span></h2>
    <div class="floatright" style="margin: 0px 0px 0.5em 0.5em; clear: right; float: right; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
    </div>
    <p style="margin: 0.5em 0px; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        In 2005, Amazon announced the creation of Amazon Prime, a membership offering free two-day shipping within the contiguous United States on all eligible purchases for a flat annual fee of $79 (equivalent to $103 in 2019),<sup id="cite_ref-primepricehike_12-0" class="reference" style="line-height: 1; unicode-bidi: isolate; white-space: nowrap; font-weight: normal; font-style: normal; font-size: 11.2px;"><a href="https://en.wikipedia.org/wiki/List_of_Amazon_products_and_services#cite_note-primepricehike-12" style="text-decoration: none; color: rgb(11, 0, 128); background: none;">[12]</a></sup><span>&nbsp;</span>as well as discounted one-day shipping rates.<sup id="cite_ref-13" class="reference" style="line-height: 1; unicode-bidi: isolate; white-space: nowrap; font-weight: normal; font-style: normal; font-size: 11.2px;"><a href="https://en.wikipedia.org/wiki/List_of_Amazon_products_and_services#cite_note-13" style="text-decoration: none; color: rgb(11, 0, 128); background: none;">[13]</a></sup><span>&nbsp;</span>Amazon 
        launched the program in Germany, Japan, and the United Kingdom in 2007; in France (as &quot;Amazon Premium&quot;) in 2008, in Italy in 2011, in Canada in 2013,<sup id="cite_ref-primecanada_14-0" class="reference" style="line-height: 1; unicode-bidi: isolate; white-space: nowrap; font-weight: normal; font-style: normal; font-size: 11.2px;"><a href="https://en.wikipedia.org/wiki/List_of_Amazon_products_and_services#cite_note-primecanada-14" style="text-decoration: none; color: rgb(11, 0, 128); background: none;">[14]</a></sup><span>&nbsp;</span>and in India on July 26, 2016.<sup id="cite_ref-15" class="reference" style="line-height: 1; unicode-bidi: isolate; white-space: nowrap; font-weight: normal; font-style: normal; font-size: 11.2px;"><a href="https://en.wikipedia.org/wiki/List_of_Amazon_products_and_services#cite_note-15" style="text-decoration: none; color: rgb(11, 0, 128); background: none;">[15]</a></sup></p>
    <p style="margin: 0.5em 0px; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        Amazon Prime membership in Germany, the United Kingdom, Canada, India, and the United States also provides<span>&nbsp;</span><span>&nbsp;</span>the instant streaming of selected movies and TV shows at no additional cost.<sup id="cite_ref-17" class="reference" style="line-height: 1; unicode-bidi: isolate; white-space: nowrap; font-weight: normal; font-style: normal; font-size: 11.2px;"><a href="https://en.wikipedia.org/wiki/List_of_Amazon_products_and_services#cite_note-17" style="text-decoration: none; color: rgb(11, 0, 128); background: none;">[17]</a></sup><span>&nbsp;</span>In 
        November 2011, it was announced that Prime members have access to the Kindle Owners’ Lending Library, which allows users to borrow certain popular Kindle e-books for free reading on Kindle hardware, up to one book a month, with no due date.</p>
    <p style="margin: 0.5em 0px; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
</asp:Content>

